config/routes.rb
Privly::Application.routes.draw do

  root :to => "welcome#index"
  match '/' => 'welcome#index', :as => :welcome, :via => [:get]

  get "users/sign_in" => redirect("/apps/Login/new.html"), :as => :sign_in

  # Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # Endpoint for destroying all the user's stored posts
  match '/posts/destroy_all' => 'posts#destroy_all', :via => :delete
  match '/user/destroy_account' => 'users#destroy', :via => :delete

  get "users/invitation/new" => redirect("/")

  # Authenticating Applications (used by mobile)
  resources :token_authentications, :only => [:create, :new]
  match "token_authentications" => "token_authentications#show", :as => :show_token_authentications, :via => [:get, :post]
  match 'token_authentications' => 'token_authentications#destroy', :as => :destroy_token_authentications, :via => [:delete]
  
  # User authentication
  devise_for :users, :controllers => { :invitations => 'users/invitations',
                                       :sessions => 'sessions',
                                       :confirmations => 'users/confirmations' }
  
  # Invitations and mailers
  devise_scope :user do
    post "users/invitations/send_invitation" => "users/invitations#send_invitation", :as => :user_send_invitations
    post "users/invitations/send_update" => "users/invitations#send_update", :as => :user_send_update
    post "users/invitations/use_invite" => "users/invitations#use_invite", :as => :user_use_invite
  end 

  #account settings and delete account
  get "pages/account"
  
  #nearly static pages
  get "pages/privacy"
  get "pages/terms" => redirect("/pages/privacy") # One central info page
  get "pages/license" => redirect("/pages/privacy") # One central info page
  
  #legacy pages
  get "pages/donate" => redirect("https://priv.ly/pages/donate")
  get "pages/download" => redirect("https://priv.ly/pages/download")
  get "pages/about" => redirect("https://priv.ly/pages/about")
  get "pages/people" => redirect("https://priv.ly/pages/about")
  get "pages/roadmap" => redirect("https://priv.ly/pages/about")
  get "pages/kickstarter" => redirect("https://priv.ly/pages/kickstarter")
  get "pages/faq" => redirect("http://www.privly.org/faq")
  get "pages/join" => redirect("http://www.privly.org/content/how-get-started")
  get "pages/irc" => redirect("http://www.privly.org/content/irc")
  get "pages/bug" => redirect("http://www.privly.org/content/bug-report")
  get "pages/email" => redirect("https://groups.google.com/forum/?fromgroups#!forum/privly")

  # Posting initialization endpoint
  match '/posts/user_account_data' => "posts#user_account_data", 
    :as => :get_user_account_data, :via => [:get]
  
  # Post storage and viewing
  resources :posts
  
  # Active Admin
  ActiveAdmin.routes(self)
  
end

app/views/notifier/pending_invitation.html.erb
<p>Hello <%= @user.email %>,</p>

<p>Thanks for signing up for an invitation on <%= Privly::Application.config.name %>!</p>

<p>We'll remember your email when we start sending out general invitations. We are prioritizing accounts on this server for developers, testers, and donors.</p>

<p>For more information about Privly, please visit one of these sources:</p>

<ul>
  <li><a href="https://groups.google.com/group/privly" target="_blank">Development Mailing List</a></li>
  <li><a href="https://groups.google.com/group/privly-test" target="_blank">Testing Mailing List</a></li>
  <li><a href="https://groups.google.com/group/privly-announce" target="_blank">Announcements Mailing List</a></li>
  <li><a href="https://www.privly.org" target="_blank">Privly Foundation Home</a></li>
  <li><a href="https://github.com/privly/privly-organization/wiki" target="_blank">Development Wiki</a></li>
  <li><a href="https://github.com/privly" target="_blank">Repository List</a></li>
  <li><a href="https://www.privly.org/content/bug-report" target="_blank">Submit a Bug</a></li>
  <li><a href="https://www.privly.org/content/irc" target="_blank">IRC</a></li>
  <li><a href="https://priv.ly/pages/download" target="_blank">Download Extension</a></li>
</ul>

<p>
    Sincerely,
    <br />
    -The <%= Privly::Application.config.name %> Team
</p>

app/views/notifier/pending_invitation.text.erb
Hello <%= @user.email %>,

Thanks for signing up for an invitation on <%= Privly::Application.config.name %>!

We'll remember your email when we start sending out general invitations. We are prioritizing accounts on this server for developers, testers, and donors.

For more information about Privly, please visit one of these sources:

* Development Mailing List: https://groups.google.com/group/privly
* Testing Mailing List: https://groups.google.com/group/privly-test
* Announcements Mailing List: https://groups.google.com/group/privly-announce
* Privly Foundation Home: https://www.privly.org
* Development Wiki: https://github.com/privly/privly-organization/wiki
* Repository List: https://github.com/privly
* Submit a Bug: https://www.privly.org/content/bug-report
* IRC: https://www.privly.org/content/irc
* Download Extension: https://priv.ly/pages/download

Sincerely,
-The <%= Privly::Application.config.name %> Team

app/views/notifier/update_invited_user.html.erb
<p>Hello <%= @user.email %>,</p>

<p>
  This email is to update you regarding recent changes on 
  <%= Privly::Application.config.name %>.
</p>

<p>
  We recently updated all the Privly Applications hosted by this server
  with numerous improvements to make it a smoother experience.
  We also added documentation to applications to help you
  understand the privacy each application is offering. If you have
  and thoughts or issues with the status of the system, please 
  <a href="https://www.privly.org/content/bug-report" target="_blank">
    submit a bug
  </a>
  or email <a href="mailto:privly@privly.org">privly@privly.org</a>.
</p>

<p>
  Sincerely,
  <br />
  -The <%= Privly::Application.config.name %> Team
</p>

<p>
  For more information about Privly, please visit one of these sources:
</p>
<ul>
  <li><a href="https://groups.google.com/group/privly" target="_blank">Development Mailing List</a></li>
  <li><a href="https://groups.google.com/group/privly-test" target="_blank">Testing Mailing List</a></li>
  <li><a href="https://groups.google.com/group/privly-announce" target="_blank">Announcements Mailing List</a></li>
  <li><a href="https://www.privly.org" target="_blank">Privly Foundation Home</a></li>
  <li><a href="https://github.com/privly/privly-organization/wiki" target="_blank">Development Wiki</a></li>
  <li><a href="https://github.com/privly" target="_blank">Repository List</a></li>
  <li><a href="https://www.privly.org/content/bug-report" target="_blank">Submit a Bug</a></li>
  <li><a href="https://www.privly.org/content/irc" target="_blank">IRC</a></li>
  <li><a href="https://priv.ly/pages/download" target="_blank">Download Extension</a></li>
</ul>

<p>
  We will not contact you via email unless there are significant changes to
  the software, organization, or your data's safety. To stop receiving these
  messages, you can destroy your user account on this server by logging in and
  visiting the <%= link_to "account page.", pages_account_url %>
</p>

app/views/notifier/update_invited_user.text.erb
Hello <%= @user.email %>,

This email is to update you regarding recent changes on <%= Privly::Application.config.name %>.

We recently updated all the Privly Applications hosted by this server with numerous improvements. We also added documentation to applications to help you understand the privacy offered by each application. If you have and thoughts or issues with the status of the system, please submit a bug or email privly@privly.org.

Sincerely,
-The <%= Privly::Application.config.name %> Team

For more information about Privly, please visit one of these sources:
* Submit a Bug: https://www.privly.org/content/bug-report
* Development Mailing List: https://groups.google.com/group/privly
* Testing Mailing List: https://groups.google.com/group/privly-test
* Announcements Mailing List: https://groups.google.com/group/privly-announce
* Privly Foundation Home: https://www.privly.org
* Development Wiki: https://github.com/privly/privly-organization/wiki
* Repository List: https://github.com/privly
* IRC: https://www.privly.org/content/irc
* Download Extension: https://priv.ly/pages/download

We will not contact you via email unless there are significant changes to the software, organization, or your data's safety. To stop receiving these messages, you can destroy your user account on this server by logging in and visiting <%= pages_account_url %>