config/routes.rb
Privly::Application.routes.draw do

  root :to => "welcome#index"
  match '/' => 'welcome#index', :as => :welcome, :via => [:get]

  get "users/sign_in" => redirect("/apps/Login/new.html"), :as => :sign_in

  # Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # Endpoint for destroying all the user's stored posts
  match '/posts/destroy_all' => 'posts#destroy_all', :via => :delete
  match '/user/destroy_account' => 'users#destroy', :via => :delete

  get "users/invitation/new" => redirect("/")

  # Authenticating Applications (used by mobile)
  resources :token_authentications, :only => [:create, :new]
  match "token_authentications" => "token_authentications#show", :as => :show_token_authentications, :via => [:get, :post]
  match 'token_authentications' => 'token_authentications#destroy', :as => :destroy_token_authentications, :via => [:delete]
  
  # User authentication
  devise_for :users, :controllers => { :invitations => 'users/invitations',
                                       :sessions => 'sessions',
                                       :confirmations => 'users/confirmations' }
  
  # Invitations and mailers
  devise_scope :user do
    post "users/invitations/send_invitation" => "users/invitations#send_invitation", :as => :user_send_invitations
    post "users/invitations/send_update" => "users/invitations#send_update", :as => :user_send_update
    post "users/invitations/use_invite" => "users/invitations#use_invite", :as => :user_use_invite
  end 

  #account settings and delete account
  get "pages/account"
  
  #nearly static pages
  get "pages/privacy"
  get "pages/terms" => redirect("/pages/privacy") # One central info page
  get "pages/license" => redirect("/pages/privacy") # One central info page
  
  #legacy pages
  get "pages/donate" => redirect("https://priv.ly/pages/donate")
  get "pages/download" => redirect("https://priv.ly/pages/download")
  get "pages/about" => redirect("https://priv.ly/pages/about")
  get "pages/people" => redirect("https://priv.ly/pages/about")
  get "pages/roadmap" => redirect("https://priv.ly/pages/about")
  get "pages/kickstarter" => redirect("https://priv.ly/pages/kickstarter")
  get "pages/faq" => redirect("http://www.privly.org/faq")
  get "pages/join" => redirect("http://www.privly.org/content/how-get-started")
  get "pages/irc" => redirect("http://www.privly.org/content/irc")
  get "pages/bug" => redirect("http://www.privly.org/content/bug-report")
  get "pages/email" => redirect("https://groups.google.com/forum/?fromgroups#!forum/privly")

  # Posting initialization endpoint
  match '/posts/user_account_data' => "posts#user_account_data", 
    :as => :get_user_account_data, :via => [:get]
  
  # Post storage and viewing
  resources :posts
  
  # Active Admin
  ActiveAdmin.routes(self)
  
end

app/views/pages/account.html.erb
<% content_for(:title) do %>
    Account
<% end %>

<% content_for(:extrajs) do %>
  <script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function(){
      
      // Make the user type a message before displaying the destroy button
      document.querySelector('#confirmation_text').addEventListener('keyup', 
        function(){
          if($("#confirmation_text").val() === 
            "I understand that this will permanently destroy my user account and the data might not be recoverable") {
            $("#confirmed_destroy_button").show();
          }
        }
      );
      
      // Show the destroy button when the user has successfully typed the
      // destroy confirmation.
      document.querySelector('#destroy_account_button').addEventListener('click', 
        function(){
          $("#type_confirmation_message").show();
        }
      );
    });
  </script>
<% end %>

<div class="page-header">
  <h1>Your <%= Privly::Application.config.name %> Account</h1>
</div>

<div id="type_confirmation_message" class="row-fluid" style="display:none;">
  <div class="span12">
    <h2>Destroy Account Confirmation</h2>
    <p>
      To destroy your account, type this message exactly: 
      "I understand that this will permanently destroy my user account and the data might not be recoverable"
    </p>
    <input id="confirmation_text" 
      type="text" 
      placeholder="I understand that this will permanently destroy my user account and the data might not be recoverable" 
      style="width:700px;"></input>
    <%= button_to 'Destroy My User Account and Posts', 
      user_destroy_account_path,
      :id => "confirmed_destroy_button",
      :confirm => 'Are you sure? This will destroy all your data.', 
      :method => :delete,
      :style => "display:none;",
      :class => "btn btn-large btn-danger" %>
    <hr />
  </div>
</div>

<div class="row-fluid">
  <div class="span7">
    <% unless current_user.can_post %>
      <p>Your user account's posting permission has been deactivated for lack of development and testing activity. If you are active in Privly development, please ask on email or IRC for it to be reactivated.</p>
    <% end %>
    <h2>Invitations</h2>
    <% if current_user.forever_account_value > 0 %>
      <p>Your user account currently has a forever account value of $<%= current_user.forever_account_value %>/month. Forever account benefits are not currently active. You will be emailed when your forever account value is active.</p>
    <% end %>
    <p>Your user account currently has <%= current_user.alpha_invites %> Alpha invites.</p>
    <% if current_user.alpha_invites > 0 %>
      <%= form_tag(user_use_invite_path, {:class => "form"}) do %>
        <p>Invite Email</p>
        <%= email_field_tag "user[email]", "" %>
        <%= submit_tag "Send Invitation", :id => "submit", :name => "submit", :class => "form_submit", :disabled => false, :disable_with => "Please wait..." %>
      <% end -%>
    <% end %>
  </div>
  <div class="span5">
    <h2>Manage Your Data</h2>
    <p>
      <%= button_to 'Export All My Posts', 
        {:controller => "posts", :action => "index", :format => :csv}, 
        :confirm => 'Are you sure? This will export all of your posts in .csv format.', 
        :method => :get, :class => "btn btn-large btn-success" %>
    </p>
    <p>
      <%= button_to 'Destroy All My Posts', posts_destroy_all_path, 
        :confirm => 'Are you sure? This will destroy everything you know and love in this site.',
        :method => :delete, :class => "btn btn-large btn-warning" %>
    </p>
    <p>
      <input id="destroy_account_button" 
        class="btn btn-large btn-danger" 
        type="button" value="Destroy My User Account and Posts" />
    </p>

    <p><strong><%= Privly::Application.config.name %> knows this about you:</strong></p>
    <p>Your <%= Privly::Application.config.name %> verified email is "<%= current_user.email %>".</p>
    <p>Your <%= Privly::Application.config.name %> verified domain is "<%= current_user.domain %>".</p>
    <p>Your current IP address is "<%= request.remote_ip %>".</p>
    <h2>Password</h2>
    <p>To change the password for the account associated with <%= current_user.email %>, <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %> and check login options to manage your password.</p>
  </div>
</div>