config/routes.rb
Privly::Application.routes.draw do

  root :to => "welcome#index"
  match '/' => 'welcome#index', :as => :welcome, :via => [:get]

  get "users/sign_in" => redirect("/apps/Login/new.html"), :as => :sign_in

  # Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # Endpoint for destroying all the user's stored posts
  match '/posts/destroy_all' => 'posts#destroy_all', :via => :delete
  match '/user/destroy_account' => 'users#destroy', :via => :delete

  get "users/invitation/new" => redirect("/")

  # Authenticating Applications (used by mobile)
  resources :token_authentications, :only => [:create, :new]
  match "token_authentications" => "token_authentications#show", :as => :show_token_authentications, :via => [:get, :post]
  match 'token_authentications' => 'token_authentications#destroy', :as => :destroy_token_authentications, :via => [:delete]
  
  # User authentication
  devise_for :users, :controllers => { :invitations => 'users/invitations',
                                       :sessions => 'sessions',
                                       :confirmations => 'users/confirmations' }
  
  # Invitations and mailers
  devise_scope :user do
    post "users/invitations/send_invitation" => "users/invitations#send_invitation", :as => :user_send_invitations
    post "users/invitations/send_update" => "users/invitations#send_update", :as => :user_send_update
    post "users/invitations/use_invite" => "users/invitations#use_invite", :as => :user_use_invite
  end 

  #account settings and delete account
  get "pages/account"
  
  #nearly static pages
  get "pages/privacy"
  get "pages/terms" => redirect("/pages/privacy") # One central info page
  get "pages/license" => redirect("/pages/privacy") # One central info page
  
  #legacy pages
  get "pages/donate" => redirect("https://priv.ly/pages/donate")
  get "pages/download" => redirect("https://priv.ly/pages/download")
  get "pages/about" => redirect("https://priv.ly/pages/about")
  get "pages/people" => redirect("https://priv.ly/pages/about")
  get "pages/roadmap" => redirect("https://priv.ly/pages/about")
  get "pages/kickstarter" => redirect("https://priv.ly/pages/kickstarter")
  get "pages/faq" => redirect("http://www.privly.org/faq")
  get "pages/join" => redirect("http://www.privly.org/content/how-get-started")
  get "pages/irc" => redirect("http://www.privly.org/content/irc")
  get "pages/bug" => redirect("http://www.privly.org/content/bug-report")
  get "pages/email" => redirect("https://groups.google.com/forum/?fromgroups#!forum/privly")

  # Posting initialization endpoint
  match '/posts/user_account_data' => "posts#user_account_data", 
    :as => :get_user_account_data, :via => [:get]
  
  # Post storage and viewing
  resources :posts
  
  # Active Admin
  ActiveAdmin.routes(self)
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= Privly::Application.config.name %> &middot; <%= yield :title %></title>

    <!-- Enable responsive viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="icon" href="/favicon.ico" />
    
    <%= stylesheet_link_tag    :bs %>
    <%= javascript_include_tag :bs %>

    <%= yield :extrahead %>
    <%= yield :extracss %>
    <%= yield :extrajs %>

    <%= csrf_meta_tags %>

  </head>

  <body>
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div id="site_name">
             <a class="brand" href="/"><%= Privly::Application.config.name %></a>
             <span>Share Priv(ate).ly</span>
          </div>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                <li>
                  <a href="/apps/Index/new.html">Privly Applications</a>
                </li>
                <li <% if controller.action_name == "account" %>class="active"<% end %>>
                  <%= link_to "Account", pages_account_path %>
                </li>
                <li <% if controller.action_name == "privacy" %>class="active"<% end %>>
                  <%= link_to "Trust Center", pages_privacy_path %>
                </li>
                <li>
                  <%= link_to "Logout", 
                  destroy_user_session_path, 
                  :method => :delete %>
                </li>
              <% else %>
                <li <% if controller.action_name == "privacy" %>class="active"<% end %>>
                  <%= link_to "Trust Center", pages_privacy_path %>
                </li>
                <li <% if controller.controller_name == "invitations" %>class="active"<% end %>>
                  <%= link_to "Sign In", sign_in_path %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container-narrow">
      
      <% if notice %>
      <div class="flash notice">
          <p><%= notice %></p>
      </div>
      <% end %>
      <% if alert %>
      <div class="flash alert">
          <p><%= alert %></p>
      </div>
      <% end %>
      
      <div class="content">
        <%= yield %>
      </div>
      <hr>
      <footer>
        <div id="btmcontent">
            <div id="downloadmessage">

              <% if firefox_browser? %>
                <div id="firefox_link" style="float: left; width: 33%;">
                    <%= link_to("https://addons.mozilla.org/en-US/firefox/addon/privly/") do %>
                      <div style="position:relative;width:10em;padding:1em;height:150px">
                        <%= image_tag "firefox_logo_150.png", :alt => "Firefox Logo", :style=>"position:absolute;right:0;top:0;opacity:0.9;filter:alpha(opacity=90);" %>
                        <%= image_tag "icons/icon_96.png", :alt => "Privly Icon", :style=>"position:absolute;right:27px;top:20px;" %>
                      </div>         
                    <% end %>
                </div>
              <% end %>

              <% if opera_browser? %>
                <div id="opera_link" style="float: left; width: 34%;">
                  <%= link_to("https://addons.opera.com/en/extensions/details/privly-2/?display=en") do %>

                    <div style="position:relative;width:10em;padding:1em;height:150px">
                      <%= image_tag "opera_logo_150.png", :alt => "Google Chrome Logo", :style=>"position:absolute;right:0;top:0;opacity:0.9;filter:alpha(opacity=90);background-color:rgba(255, 255, 255, 0.08);" %>
                      <%= image_tag "icons/icon_96.png", :alt => "Privly Icon", :style=>"position:absolute;right:27px;top:20px;" %>
                    </div>
                  <% end %>
                </div>
              <% end %>

              <% if chrome_browser? %>
                <div id="chrome_link" style="float: left; width: 33%;">
                  <%= link_to("https://chrome.google.com/webstore/detail/pkokikcdapfpkkkjpdaamjanniaempol") do %>
                    <div style="position:relative;width:10em;padding:1em;height:150px">
                      <%= image_tag "chrome-logo_150X.png", :alt => "Google Chrome Logo", :style=>"position:absolute;right:0;top:0;opacity:0.9;filter:alpha(opacity=90);" %>
                      <%= image_tag "icons/icon_96.png", :alt => "Privly Icon", :style=>"position:absolute;right:33px;top:15px;" %>
                    </div>
                  <% end %>
                </div>
              <% end %>

              <h2>Never View this Site Again</h2>
              <p>Privly works by injecting status updates, emails, tweets... anything really... directly into pages you view everyday. We never want you to come back to this website again. <%= link_to "Download", "https://priv.ly/pages/download" %> the extension and you won't have to.</p>
            </div><!-- downloadmessage -->
        </div><!-- btmcontent -->
      </footer>
      
    </div>
    
    <%= javascript_include_tag :bootstrap %>
  </body>
</html>